### ISSUE TITLE
[Feature Request and some bugs] Full Greggification!

### ISSUE THREAD

**Issue by OneEyeMaker** [Vexatos/TinkersGregworks#24] opened 2016-03-26 07:32 UTC
Hello!
I'm creating modpack with GT, TiCon and TGreg. And I want to fully "Greggify" TiCon tools by removing all non-GT materials (copper, obsidian, alumite, ardite, manyullin, etc.) and redefining all TiCon mining levels (transform it to GT's ones).

Now I can only partially disable recipes for non-GT tool parts with Mine-/ModTweaker and Iguana's TiCon Tweaks.
But I can't remove/disable recipes, that TGregworks add for these materials (for example, Fluid Solidifier recipes for any bolts with copper, obsidian, etc. arrowhead).
Second task - replace all TiCon's mining levels ("Stone", "Copper", "Iron", "Tin", "Redstone", "Obsidian", "Cobalt", "Ardite", "Manyullyn") with GT's ones (Levels 0-6) I can do only partially with Iguana's TiCon Tweaks.

Would be very nice, if you realize all this in TGregworks:
- Remove *all* materials from TiCon (if it's impossible - remove recipes of tool parts and hide ones in NEI);
- Add *all* materials from GT (It should require "addMaterialsAnyway=true");
- Add recipes *only* for GT's materials;
- Add simple recipes for all tool parts from low-level materials (wood, stone and flint);
- (If possible) Reorganize TiCon's mining levels.

And, finally, add config option for enabling this functional.

Thank you very much for your work!
P. S. Sorry for my English, I'm from Russia.

**Comment by Vexatos** [comment] 2016-03-26 14:21
>Add all materials from GT

The config option `addMaterialsAnyway` should do exactly that: It should add tool parts for every GregTech material that can be crafted into GregTech tools (i.e. if you can make a GregTech pickaxe head with it, you can make a TGw pickaxe head, too). The config option just got fixed in version 1.0.10, you might want to try that.

>Remove all materials from TiCon 

Eh, this mod actually doesn't do that on purpose. It is not supposed to "greggify" TCon; instead, it rather extends it. I... I am not sure. And I am pretty sure you can remove tool materials using ModTweaker.

> Add recipes only for GT's materials

I never added recipes for tool materials not added by TGregworks. enabling `addMaterialsAnyway` should for instance add recipes for TGregworks's steel tool parts, but it shouldn't touch The steel parts added by TCon itself

>(If possible) Reorganize TiCon's mining level

as I said, I do not touch TCon's materials at all. TGregworks' mining levels are aligned to GregTech's tool mining levels (e.g. a Cobalt Pickaxe head has the exact same mining level as a GregTech Cobalt pickaxe)

>Add simple recipes for all tool parts from low-level materials (wood, stone and flint);

But can't you just... not disable those materials and disable everything else using ModTweaker?

**Comment by OneEyeMaker** [comment] 2016-03-26 15:00
OK, I understood your position. Thank you for answer.

**Comment by Vexatos** [comment] 2016-03-26 15:39
This mod is not for changing TCon itself, use ModTweaker for that. Thanks for understanding.

**Comment by OneEyeMaker** [comment] 2016-03-26 16:55
Ok. I understand it. I try to make that myself.

And... I found strange behavior... (TGreg v1.0.10)
I found duplicates in bolt recipes (in Fluid Solidifier) for parts from TGregworks. Also I found recipes with tool rod form TGregworks and... fluid from TiCon (rather, its' analogues from GT)!
See here: http://imgur.com/a/sv832
1) Stainless steel bolt with rubber arrowhead (it's OK).
2) Stainless steel bolt with rubber arrowhead (duplicate?).
3) Stainless steel bolt with obsidian arrowhead... 
And see amount of recipes to create Stainless steel bolt: 225.
But if "addMaterialsAnyway" is disabled, I have only 107 recipes to create bolt from any TiCon material (but for any material from TGregworks still have 225 recipes).

Also, if "addMaterialsAnyway" is enabled, I have two variants of each bolt from TiCon's materials.
For example, I have two cobalt bolts (first with material ID = 10 - TiCon, second with material ID 1505 - TGreg). And first one have 107 recipes in Fluid Solidifier, second - 225.

Please, if "addMaterialsAnyway" is enabled:
- Don't add recipes for bolts from TiCon; only add recipes for bolts from TGreg (I can't remove Fluid Solidifier recipes with MineTweaker+ModTweaker+GTTweaks, I can only add ones).
- Add config option to disable adding bolt recipes with arrowheads from obsidian, copper, ardite (and other materials, from which no instruments are in GT).

**Comment by Vexatos** [comment] 2016-03-27 20:23
No idea about the duplicate recipes, I'll look into it.
For recipes, there's supposed to be a lot: One for every combination of TGregworks tool rod and GregTech or TCon molten material.

**Comment by OneEyeMaker** [comment] 2016-03-28 06:55
OK.

And I think, that I found what cause this bugs.
See [here](https://github.com/Vexatos/TinkersGregworks/blob/master/src/main/java/vexatos/tgregworks/integration/TGregRecipeRegistry.java#L228).

I only renamed variables and added marks in comments:
```
LiquidCasting tableCasting = TConstructRegistry.getTableCasting();
// (1):
for (Map.Entry<String, FluidType> fluidEntry : FluidType.fluidTypes.entrySet())
{
    if (!fluidEntry.getValue().isToolpart)
    {
        continue;
    }
    int arrowheadMaterialID;
    FluidStack liquid = new FluidStack(entry.getValue().fluid, TConstruct.ingotLiquidValue);
    // (2):
    if (fluidEntry.getValue() instanceof TGregFluidTyoe)
    {
        arrowheadMaterialID = ((TGregFluidType) entry.getValue()).matID;
        // (3)
        for (Integer toolRodMaterialID : TConstructRegistry.toolMaterials.keySet())
        {
            ItemStack toolRod = new ItemStack(TinkerTools.toolRod, 1, id);
            if(((IToolPart) TinkerTools.toolRod).getMaterialID(toolRod) == -1) {
                continue;
            }
            // (4):
            Materials arrowheadMaterial = ((TGregFluidType) fluidEntry.getValue()).material;
            GT_Values.RA.addFluidSolidifierRecipe(
                toolRod,
                liquid.copy(),
                DualMaterialToolPart.createDualMaterial(TinkerWeaponry.partBolt, toolRodMaterialID, arrowheadMaterialID),
                80 + arrowheadMaterial.mDurability * 2, getPowerRequired(arrowheadMaterial)
            );
        }
    }
    // (5)
    else
    {
        CastingRecipe recipe = tableCasting.getCastingRecipe(liquid, new ItemStack(TinkerSmeltery.metalPattern, 1, 2));
        if(recipe == null) 
        {
            continue;
        } 
        else 
        {
            arrowheadMaterialID = recipe.getResult().getItemDamage();
        }
    }
    // (6):
    for(Map.Entry<Materials, Integer> materialEntry : TGregworks.registry.matIDs.entrySet()) 
    {
        // (7):
        Materials toolRodMaterial = materialEntry.getKey();
        ItemStack toolRod = TGregUtils.newItemStack(toolRodMaterial, PartTypes.ToolRod, 1);
        GT_Values.RA.addFluidSolidifierRecipe(
            toolRod,
            liquid.copy(),
            DualMaterialToolPart.createDualMaterial(TinkerWeaponry.partBolt, materialEntry.getValue(), arrowheadMaterialID),
            80 + (toolRodMaterial.mDurability * 2), getPowerRequired(toolRodMaterial)
        );
    }
}
```

Order of your actions:
Step 1) For each fluid (1) you get id of material for arrowhead (2,  5);
Step 2) If fluid is from GT (2), for each material for tool rod (3) you add Fluid Solidifier recipe (4). *__Summary of step:__ 107 recipes for each bolt from TCon and 107 recipes for each bolt from TGreg. Time in each recipe depends on material of arrowhead.*
Step 3) For all fluids (1, 2, 5) for each tool rod from TGreg (6) you add Fluid Solidifier recipe (7). *__Summary of step:__ 107 recipes for each bolt from TGreg with GT fluids and about 10 recipes for each bolt from TGreg with TCon fluids. Time in each recipe depends on material of tool rod.*

Summary: Each TCon bolt has 107 recipes, each TGreg bolt has 107 + 107 + (about) 10 recipes (225 in my case).
I hope, you see, that you add duplicate recipes on step 3. Also on step 2 you add recipes for bolts from TCon's materials even if you override these materials (i. e. "addMaterialsAnyway=true"). Finally, [this](https://github.com/Vexatos/TinkersGregworks/blob/master/src/main/java/vexatos/tgregworks/integration/TGregRecipeRegistry.java#L275) code looks strange... (Does it cancels code, marked as (5) above?)

Please, refactor this method (```registerBoltRecipes()```) and fix these bugs.
Thank you for your work!)))
//Sorry for my English...

**Comment by Vexatos** [comment] 2016-03-28 14:22
Thanks for tracking down the issue, I am indeed registering recipes for TGw tool rods twice. I will add a check to the first loop to make it ignore TGw tool rods as those are covered by the second.

For disabling bolt recipes involving TCon materials I will probably add a new config option.

The mentioned code removes recipes that TCon adds automatically, namely bolt recipes involving tool rods with TGw material IDs. The problem is that it uses the TCon tool rod item and gives it a metadata corresponding to the material ID, but TGw tool rods are an entirely different Item instance and thus a TCon tool rod with that material ID doesn't even exist. That's why I am adding the correct bolt recipes manually and removing the broken ones.

**Comment by OneEyeMaker** [comment] 2016-03-28 16:43
Ok.
I'll wait new release with correct bolt recipes and config options:
 - to disable adding recipes with TCon's tool rods, if TGreg adds the similar ones and
 - to disable adding recipes with fluids from TCon ("Only GT").

Thank you for your work *very much*!

**Comment by Vexatos** [comment] 2016-03-29 16:27
@OneEyeMaker Wouldn't a single config option for both work? It would essentially not add any Fluid Solidifier recipe involving either non-GT fluids or non-TGw tool rods. Would that be okay?

**Comment by OneEyeMaker** [comment] 2016-03-29 21:22
I again thought about realization of this functionality. I think, for now it will be enough *one* config option - "useNonGTFluidsForBolts".
I wrote some code for you.
```
import tconstruct.library.tools.ToolMaterial;

//add before method 'registerBoltRecipes()':
private boolean addMaterialsAnyway = TGregworks.config.getBoolean("addMaterialsAnyway", Config.Category.General, false, "Register Materials even if a material with the same name already exists. May override any material with the same name added by other mods.");
private boolean useNonGTFluidsForBolts = TGregworks.config.getBoolean("useNonGTFluidsForBolts", Config.Category.General, true, "Register Fluid Solidifier recipes for bolts with non-GT fluids.");
private int latestAvailableNumber = TGregworks.config.getInt("materialIDRangeStart", Config.Category.General, 1500, 300, 15000, "The lowest ID for TGregworks materials. Only material IDs higher than this will be used, and only if the ID has not been registered before. Other mods might not check if the material ID is already in use and thus crash, if the crash occurs with a TGregworks material, changing this number may fix it.");

//replace loop in method 'registerBoltRecipes()':
LiquidCasting tableCasting = TConstructRegistry.getTableCasting();
for (Map.Entry<String, FluidType> fluidEntry : FluidType.fluidTypes.entrySet())
{
    if (!fluidEntry.getValue().isToolpart)
    {
        continue;
    }
    FluidStack liquid = new FluidStack(entry.getValue().fluid, TConstruct.ingotLiquidValue);
    int arrowheadMaterialID;
    if (fluidEntry.getValue() instanceof TGregFluidTyoe)
    {
        arrowheadMaterialID = ((TGregFluidType) entry.getValue()).matID;
    }
    else
    {
        CastingRecipe recipe = tableCasting.getCastingRecipe(liquid, new ItemStack(TinkerSmeltery.metalPattern, 1, 2));
        if(recipe == null) 
        {
            continue;
        } 
        else 
        {
            arrowheadMaterialID = recipe.getResult().getItemDamage();
        }
    }
    ToolMaterial arrowheadMaterial = TConstructRegistry.toolMaterials.get(arrowheadMaterialID);
    for (Map.Entry<Integer, ToolMaterial> materialEntry : TConstructRegistry.toolMaterials.entrySet())
    {
        int toolRodMaterialID = materialEntry.getKey();
        ToolMaterial toolRodMaterial = materialEntry.getValue();
        ItemStack toolRod = new ItemStack(TinkerTools.toolRod, 1, toolRodMaterialID);
        if(((IToolPart) TinkerTools.toolRod).getMaterialID(toolRod) == -1) {
            continue;
        }
        // in this hierarchy of 'if' expressions you can add handling of new config options (for bolts crafting) later:
        if (fluidEntry.getValue() instanceof TGregFluidTyoe || useNonGTFluidsForBolts)
        {
            if (addMaterialsAnyway)
            {
                if (TGregRegistry.materialIDMap.containsKey(toolRodMaterialID) || !TGregRegistry.toolMaterialNames.contains(toolRodMaterial.materialName))
                {
                    GT_Values.RA.addFluidSolidifierRecipe(
                        toolRod,
                        liquid.copy(),
                        DualMaterialToolPart.createDualMaterial(TinkerWeaponry.partBolt, toolRodMaterialID, arrowheadMaterialID),
                        80 + (toolRodMaterial.durability + arrowheadMaterial.durability) * 2,
                        Math.max(getPowerRequired(toolRodMaterial), getPowerRequired(arrowheadMaterial))
                    );
                }
            }
            else
            {
                GT_Values.RA.addFluidSolidifierRecipe(
                    toolRod,
                    liquid.copy(),
                    DualMaterialToolPart.createDualMaterial(TinkerWeaponry.partBolt, toolRodMaterialID, arrowheadMaterialID),
                    80 + (toolRodMaterial.durability + arrowheadMaterial.durability) * 2,
                    Math.max(getPowerRequired(toolRodMaterial), getPowerRequired(arrowheadMaterial))
                );
            }
        }
    }
}

//add after method 'registerBoltRecipes()':
//it's analogue of 'getPowerRequired(Materials)' for TCon's ToolMaterial
private int getPowerRequired(ToolMaterial toolMaterial) {
    return Math.round(toolMaterial.harvestLevel < 3 ? (30 * energyMultiplier) : (120 * energyMultiplier));
}
```

This code shouldn't add duplicated recipes at all. 
I didn't check it (may be there is some small mistakes/typo). And this code allows to simply add new config options, which controls adding of recipes.
This code realizes the following idea of configuration:
- addMaterialsAnyway=false, useNonGTFluidsForBolts=true => (all TCon's tool rods + all standard TGreg's tool rods) * all fluids;
- addMaterialsAnyway=false, useNonGTFluidsForBolts=false => (all TCon's tool rods + all standard TGreg's tool rods) * all GT fluids;
- addMaterialsAnyway=true, useNonGTFluidsForBolts=true => (all TGreg's tool rod + remaining TCon's tool rods) * all fluids;
- addMaterialsAnyway=true, useNonGTFluidsForBolts=false =>(all TGreg's tool rods + remaining TCon's tool rods) * all GT fluids.

I hope, you understand me and this code works properly. If so, please, check and apply this code and close this issue.

**Comment by Vexatos** [comment] 2016-03-30 10:33
Pretty sure the `if (addMaterialsAnyway)` should not be necessary as `TGregRegistry.materialIDMap` doesn't contain the duplicate materials if that is `false`. And not sure what you are trying to achieve with `!TGregRegistry.toolMaterialNames.contains(toolRodMaterial.materialName)`

**Comment by OneEyeMaker** [comment] 2016-03-30 14:52
Ok... To write code after midnight wasn't a good idea...
[Second attempt to fix bugs](http://pastebin.com/MuApQhij)

And in previous solution I tried to use ```!TGregRegistry.toolMaterialNames.contains(toolRodMaterial.materialName)``` for following purpose: don't add recipe with tool rod, if this one isn't from TGreg, bug TGreg has tool rod with the same name ("addMaterialsAnyway=true"). In current (second) attempt to fix I don't add this code. (With this code TGreg will add recipes for bolts from both TCon's and TGreg's variants of wood, stone, flint, bronze and cobalt, if "addMaterialsAnyway" is enabled. But these bolts are unobtainable with machines from GT, because TGreg adds recipes only for TGreg's tool rods).
I hope, that I fixed problem with ItemStack for tool rod. Now mod should check material id and gets ItemStack based on its value.

Please, say me, does this code works properly or not. And close issue, if it does and it fixes issue with recipe duplication for TGreg's bolts.

**Comment by Vexatos** [comment] 2016-03-30 16:02
Hm. This attempt looks fine. I will test it once I am back from vacation.

**Comment by Vexatos** [comment] 2016-03-30 16:05
It turns out you aren't checking for either the fluid type or the tool rod to be from TGw, meaning your method will also add fluid solidifier recipes of non-GT fluids with non-TGw tool rods to produce completely non-GT bolts. Is that intentional?

**Comment by OneEyeMaker** [comment] 2016-03-30 16:33
Yes. Anyone can configure mod to add recipes in Solidifier from "Only for GT fluids only for GT materials" to "For any fluids and materials" (= Greggify standard TCon's bolts).
This is cool, isn't it?

And, may be, you can change names and functionality of two config options, that I implemented, to allow adding recipes for any tool part in this manner... (I'm speaking about "useNonGTFluidsForBolts" and "useNonGTToolRodsForBolts".)
You can change it to "addRecipesForNonGTFliods" and "addRecipesForNonGTMaterials". And if these options are enabled, mod would add recipes in GT machines for **_any_** toolpart in TCon (+TGreg+addons for TCon). If these options are disabled - mod would add recipes only for its own tool parts. (see condition [here](http://pastebin.com/MuApQhij) at line 49).

**Comment by Vexatos** [comment] 2016-03-30 17:34
Again, I do not really want TGw to interfere with TCon at all and I'd rather like it not to touch anything that isn't related to GT. I will probably add a check to make sure it only adds a recipe if either the tool rod or the fluid type is related to GregTech.

**Comment by OneEyeMaker** [comment] 2016-03-30 18:09
I only suggested that as an option. In any case, **you** select final solution. I think, that integration "out of the box" is very good feature. If you don't like it, you can simply set these options to "false" by default.
And finally, in any case players can add needed recipes with Mine-/Mod-/GTTweaker. (*But, IMHO, to toggle value of config option much simplier, than to implement functionality with scripts.*).

**Comment by Vexatos** [comment] 2016-03-30 18:12
Well with your implementation, there is _no way_ to make it only add recipes if either the tool rod or the fluid is from GT.

**Comment by OneEyeMaker** [comment] 2016-03-30 18:37
There *is* way.
if you want add recipes only if either material of tool rod from GT or material of arrowhead from GT, you can simply add this code after line 51 in my implementation:
```
// ... big 'if' here
if (!TGregRegistry.materialIDMap.containsKey(toolRodMaterialID) &&
    !fluidEntry.getValue() instanceof TGregFluidType)
{
    continue;
}
// ... 'this.addBoltRecipe()' here
```

**Comment by Vexatos** [comment] 2016-03-30 18:57
Exactly my point. I was talking about _your implementation_ which didn't have this option.
Once I am back home, I will test this. Thanks for your work!

**Comment by OneEyeMaker** [comment] 2016-03-30 19:01
Nice to talk and work with you. Thank you for mod!

**Closed** 2016-04-01 08:35 UTC
Labels: enhancement

**Comment by Vexatos** [comment] 2016-04-01 08:37
1.0.11 is released. Go give it a try!
